server:
  port: 7777

spring:
  datasource:
    name: userDemo
    url: jdbc:h2:mem:userDemo
    username: admin
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true